#!/bin/sh
killall athol WPEWebProcess WPENetworkProcess &> /dev/null

export XDG_RUNTIME_DIR=/root/shm/wayland
rm -rf $XDG_RUNTIME_DIR
mkdir -p $XDG_RUNTIME_DIR
chmod 0700 $XDG_RUNTIME_DIR

export ATHOL_SHELL=/usr/lib/libWPEAtholShell.so

# FIXME: gst-gl's dispmanx backend is messing up with our compositor
# when it creates its initial 16x16px surface.
export GST_GL_WINDOW=dummy

# Use cairo noaa compositor
export CAIRO_GL_COMPOSITOR=noaa

# Network Process
export WPE_NETWORK_PROCESS=1

# WebInspector
#export WEBKIT_INSPECTOR_SERVER=0.0.0.0:9998

# FPS
#export WPE_THREADED_COMPOSITOR_FPS=1
#export WPE_LAYER_TREE_HOST_FPS=1

# Pointer support
#export ATHOL_POINTER_EVENTS=1

export TZ=$(wget -qO- http://jsonip.metrological.com/ | sed -e 's/^.*"tz":"\([^"]*\)".*$/\1/')

WPE_CONF_FILE="/boot/wpe.conf"
WPE_CONFIG=""
if [ -e "$WPE_CONF_FILE" ];
then
	WPE_CONFIG=$(grep -v '^#' $WPE_CONF_FILE | tr -d "\r" | tr "\n" " " | tr -s " ")
fi

# The PREFIX env var can be useful when debugging athol with gdbserver.
if [ "$1" = "--loop" ];
then
	export HOME=/root
	while true;
	do
		eval "WPE_SHELL_URL=$2 $WPE_CONFIG $PREFIX athol"
	done
else
	eval "WPE_SHELL_URL=$1 $WPE_CONFIG $PREFIX athol"
fi
