################################################################################
#
# webbridge
#
################################################################################

# WEBBRIDGE_VERSION = 00a5981f771edc475aa5568f1cdd660d6aae2189
WEBBRIDGE_VERSION = master
WEBBRIDGE_SITE_METHOD = git
WEBBRIDGE_SITE = git@github.com:Metrological/webbridge.git
WEBBRIDGE_INSTALL_STAGING = YES
WEBBRIDGE_INSTALL_TARGET = YES
WEBBRIDGE_DEPENDENCIES += cppsdk

CPPSDK_CONF_OPT += \
    -DCMAKE_TOOLCHAIN_FILE=$(HOST_DIR)/usr/share/buildroot/toolchainfile.cmake

ifeq ($(BR2_PACKAGE_WEBBRIDGE_PLUGIN_FANCONTROL),y)
  CPPSDK_CONF_OPT += \
	  -DWEBBRIDGE_INCLUDE_FAN_CONTROL=true
else
  CPPSDK_CONF_OPT += \
	  -DWEBBRIDGE_INCLUDE_FAN_CONTROL=false
endif

ifeq ($(BR2_PACKAGE_WEBBRIDGE_PLUGIN_TRACECONTROL),y)
  CPPSDK_CONF_OPT += \
	  -DWEBBRIDGE_INCLUDE_TRACE_CONTROL=true
else
  CPPSDK_CONF_OPT += \
	  -DWEBBRIDGE_INCLUDE_TRACE_CONTROL=false
endif

ifeq ($(BR2_PACKAGE_WEBBRIDGE_PLUGIN_DELAYEDRESPONSE),y)
  CPPSDK_CONF_OPT += \
	  -DCPPSDK_INCLUDE_DELAYED_RESPONE=true
else
  CPPSDK_CONF_OPT += \
	  -DCPPSDK_INCLUDE_DELAYED_RESPONE=false
endif

ifeq ($(BR2_PACKAGE_WEBBRIDGE_PLUGIN_SURFACECOMPOSITOR),y)
  CPPSDK_CONF_OPT += \
	  -DCPPSDK_INCLUDE_SURFACE_COMPOSITOR=true
else
  CPPSDK_CONF_OPT += \
	  -DCPPSDK_INCLUDE_SURFACE_COMPOSITOR=false
endif

$(eval $(cmake-package))
