#!/bin/sh

start() {
	if [ -f /usr/bin/refsw_server ] ; then
		# The "original" refsw_server has a hard-coded
		# requirment for eth0 vlan 3 with the given IP
		# address, if it is not available, the refsw_server
		# will chrash, not a pretty sight :-)
		vconfig add eth0 3
		ifconfig eth0.3 192.168.17.10
		sleep 3
		/usr/bin/refsw_server -mode unprotected &
	fi
}

case "$1" in
	start)
		start
		;;
	*)
		echo "Usage: $0 {start}"
		exit 1
esac

exit $?
