#!/bin/sh

start() {
	echo -n "Starting Horizon UI: "
	/usr/bin/horizonui &
	echo "OK"
}
stop() {
	echo -n "Stopping Horizon UI: "
	killall horizonui
	echo "OK"
}
restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
