{
'variables': {
  'QT5': '1',
  'WD_CONFIG_QWIDGET_BASE': '1',
  'WD_CONFIG_WEBKIT': '1',
  'WD_CONFIG_QUICK': '0',
  'WD_BUILD_MONGOOSE': '1',
  'WD_CONFIG_PLAYER': '0',
  'WD_CONFIG_ONE_KEYRELEASE': '0',

  'QT_INC_PATH': '$(QTINCPATH)',
  'QT_BIN_PATH': '$(QTBINPATH)',
},
}
