#!/bin/sh

start() {
	echo -n "Starting node server on port 8080: "
	node /home/applications/rpi-server/server.js &

	sleep 3

	echo -n "Starting mlbrowser: "
	qtbrowser --url=http://localhost:8080/client/index.html &

	echo "OK"
}
stop() {
	echo -n "Stopping node server: "
	killall node

	echo -n "Stopping mlbrowser: "
	killall qtbrowser

	echo "OK"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
	;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
